# Generated by Django 3.2.2 on 2021-05-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=100)),
                ('post_time', models.TimeField(auto_now=True)),
                ('post_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
